---
Namespace: Delphinus.OTAPI

CustomSerializers:
  ushort[]: Serializers.Serialize(writer, value)
  short[]: Serializers.Serialize(writer, value)
  float[]: Serializers.Serialize(writer, value)
  NetLiquidData[]: Serializers.Serialize(writer, value)
  Vector2: Serializers.Serialize(writer, value)
  Color: Serializers.Serialize(writer, value)
  BitsByte: Serializers.Serialize(writer, value)
  MultiToolMode: Serializers.Serialize(writer, value)
  NetworkText: Serializers.Serialize(writer, value)
  PlayerDeathReason: Serializers.Serialize(writer, value)
  PlayerSpawnContext: Serializers.Serialize(writer, value)
  SkyEntityType: Serializers.Serialize(writer, value)
  SubPacketType: Serializers.Serialize(writer, value)
  TeleportPylonType: Serializers.Serialize(writer, value)
  BestiaryUnlockType: Serializers.Serialize(writer, value)
  ParticleOrchestraType: Serializers.Serialize(writer, value)
  ParticleOrchestraSettings: Serializers.Serialize(writer, value)
  TileEntity: Serializers.Serialize(writer, value)

CustomDeserializers:
  byte[]: Serializers.DeserializeBytes(reader, {{args0}})
  ushort[]: Serializers.DeserializeUInt16Array(reader, {{args0}})
  short[]: Serializers.DeserializeInt16Array(reader, {{args0}})
  float[]: Serializers.DeserializeSingleArray(reader, {{args0}})
  NetLiquidData[]: Serializers.DeserializeNetLiquidData(reader, {{args0}})
  Vector2: Serializers.DeserializeVector2(reader)
  Color: Serializers.DeserializeColor(reader)
  BitsByte: Serializers.DeserializeBitsByte(reader)
  MultiToolMode: Serializers.DeserializeMultiToolMode(reader)
  NetworkText: Serializers.DeserializeNetworkText(reader)
  PlayerDeathReason: Serializers.DeserializePlayerDeathReason(reader)
  PlayerSpawnContext: Serializers.DeserializePlayerSpawnContext(reader)
  SkyEntityType: Serializers.DeserializeSkyEntityType(reader)
  SubPacketType: Serializers.DeserializeSubPacketType(reader)
  TeleportPylonType: Serializers.DeserializeTeleportPylonType(reader)
  BestiaryUnlockType: Serializers.DeserializeBestiaryUnlockType(reader)
  ParticleOrchestraType: Serializers.DeserializeParticleOrchestraType(reader)
  ParticleOrchestraSettings: Serializers.DeserializeParticleOrchestraSettings(reader)
  TileEntity: Serializers.DeserializeTileEntity(reader)

NetModuleSerializers:
  ICreativePower: Serializers.Serialize(writer, value, playerSlot)

NetModuleDeserializers:
  ICreativePower: Serializers.DeserializeCreativePowers(reader, playerSlot)

UsingStatements:
  - using System.IO;
  - using Microsoft.Xna.Framework;
  - using Terraria;
  - using Terraria.Localization;
  - using Terraria.DataStructures;
  - using Terraria.GameContent;
  - using Terraria.GameContent.Ambience;
  - using Terraria.GameContent.Creative;
  - using Terraria.GameContent.UI;
  - using Terraria.GameContent.Drawing;
  - using static Terraria.GameContent.UI.WiresUI.Settings;
  - using static Terraria.GameContent.NetModules.NetTeleportPylonModule;
  - using static Terraria.GameContent.NetModules.NetBestiaryModule;

Packets:
  ClientHello: 1
  Kick: 2
  LoadPlayer: 3
  SyncPlayer: 4
  SyncEquipment: 5
  RequestWorldInfo: 6
  WorldData: 7
  RequestTileData: 8
  StatusText: 9
  TileSection: 10
  FrameSection: 11
  SpawnPlayer: 12
  PlayerControls: 13
  PlayerActive: 14
  Unused15: 15
  PlayerHealth: 16
  TileChange: 17
  MenuSunMoon: 18
  ChangeDoor: 19
  TileSquare: 20
  SyncItem: 21
  ItemOwner: 22
  SyncNPC: 23
  UnusedStrikeNPC: 24
  ChatText: 25
  HurtPlayer: 26
  SyncProjectile: 27
  StrikeNPC: 28
  KillProjectile: 29
  PlayerPvP: 30
  RequestChestOpen: 31
  SyncChestItem: 32
  SyncPlayerChest: 33
  ChestUpdates: 34
  HealEffect: 35
  PlayerZone: 36
  RequestPassword: 37
  SendPassword: 38
  ResetItemOwner: 39
  PlayerTalkingNPC: 40
  ItemAnimation: 41
  PlayerMana: 42
  ManaEffect: 43
  KillPlayer: 44
  PlayerTeam: 45
  RequestReadSign: 46
  ReadSign: 47
  LiquidUpdate: 48
  StartPlaying: 49
  PlayerBuffs: 50
  Assorted1: 51
  Unlock: 52
  AddNPCBuff: 53
  SendNPCBuffs: 54
  AddPlayerBuff: 55
  SyncNPCName: 56
  TileCounts: 57
  PlayNote: 58
  HitSwitch: 59
  NPCHome: 60
  SpawnBoss: 61
  Dodge: 62
  PaintTile: 63
  PaintWall: 64
  Teleport: 65
  SpiritHeal: 66
  ClientUUID: 68
  ChestName: 69
  BugCatching: 70
  BugReleasing: 71
  TravelMerchantItems: 72
  TeleportationPotion: 73
  AnglerQuest: 74
  AnglerQuestFinished: 75
  AnglerQuestCountSync: 76
  TemporaryAnimation: 77
  InvasionProgressReport: 78
  PlaceObject: 79
  SyncPlayerChestIndex: 80
  CombatTextInt: 81
  NPCKillCountDeathTally: 83
  PlayerStealth: 84
  QuickStackChests: 85
  TileEntitySharing: 86
  TileEntityPlacement: 87
  ItemTweaker: 88
  ItemFrameTryPlacing: 89
  InstancedItem: 90
  SyncEmoteBubble: 91
  SyncExtraValue: 92
  SocialHandshake: 93
  MurderSomeoneElsesProjectile: 95
  TeleportPlayerThroughPortal: 96
  AchievementMessageNPCKilled: 97
  AchievementMessageEventHappened: 98
  MinionRestTargetUpdate: 99
  TeleportNPCThroughPortal: 100
  UpdateTowerShieldStrengths: 101
  NebulaLevelupRequest: 102
  MoonlordCountdown: 103
  ShopOverride: 104
  GemLockToggle: 105
  PoofOfSmoke: 106
  SmartTextMessage: 107
  WiredCannonShot: 108
  MassWireOperation: 109
  MassWireOperationPay: 110
  ToggleParty: 111
  SpecialFX: 112
  CrystalInvasionStart: 113
  CrystalInvasionWipeAllTheThings: 114
  MinionAttackTargetUpdate: 115
  CrystalInvasionSendWaitTime: 116
  PlayerHurtV2: 117
  PlayerDeathV2: 118
  CombatTextString: 119
  Emoji: 120
  TEDisplayDollItemSync: 121
  RequestTileEntityInteraction: 122
  WeaponsRackTryPlacing: 123
  TEHatRackItemSync: 124
  SyncTilePicking: 125
  SyncRevengeMarker: 126
  RemoveRevengeMarker: 127
  LandGolfBallInCup: 128
  FinishedConnectingToServer: 129
  FishOutNPC: 130
  TamperWithNPC: 131
  PlayLegacySound: 132
  FoodPlatterTryPlacing: 133
  UpdatePlayerLuckFactors: 134
  DeadPlayer: 135
  SyncCavernMonsterType: 136
  RequestNPCBuffRemoval: 137
  ClientSyncedInventory: 138
  SetCountsAsHostForGameplay: 139
  SetMiscEventValues: 140

NetModulePacketID: 82

NetModules:
  NetLiquidModule: 0
  NetTextModule: 1
  NetPingModule: 2
  NetAmbienceModule: 3
  NetBestiaryModule: 4
  NetCreativeUnlocksModule: 5
  NetCreativePowersModule: 6
  NetCreativeUnlocksPlayerReportModule: 7
  NetTeleportPylonModule: 8
  NetParticlesModule: 9
  NetCreativePowerPermissionsModule: 10